FROM node:18-slim

# Dossier de travail
WORKDIR /app

# Copier uniquement les fichiers nécessaires d'abord
COPY frontend/package.json frontend/package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier le reste de l'application
COPY frontend ./

# Vérifier que npm est installé et son chemin
RUN npm -v
RUN node -v

# Exposer le port HTTP
EXPOSE 5173

# Commande pour démarrer le serveur Vite en mode développement
CMD ["npm", "run", "dev", "--host"]