# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  upload_profiles: "%kernel.project_dir%/public/uploads/images/profiles/"
  upload_projects: "%kernel.project_dir%/public/uploads/images/projects/"
  upload_skills: "%kernel.project_dir%/public/uploads/images/skills/"
  upload_experiences: "%kernel.project_dir%/public/uploads/images/experiences/"

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Security\AuthenticationSuccessHandler:
    tags:
      - { name: kernel.event_subscriber }

  App\Security\LoginSuccessHandler:
    arguments:
      $jwtManager: "@lexik_jwt_authentication.jwt_manager"
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Service\SluggerService:
    arguments:
      $slugger: "@slugger"
  # Ajoute explicitement le service de ton EventSubscriber
  App\EventSubscriber\SlugSubscriber:
    arguments:
      $slugger: '@App\Service\SluggerService' # service SluggerService dans le Subscriber
    tags: ['doctrine.event_subscriber'] # event subscriber pour Doctrine

  App\EventListener\JWTCreatedListener:
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_created,
        }

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\ApiResource\ProjectProvider:
    autowire: true
    autoconfigure: true

  App\OpenApi\JwtDecorator:
    decorates: "api_platform.openapi.factory"
    arguments: ['@App\OpenApi\JwtDecorator.inner']
    autoconfigure: false
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\EventListener\JWTExceptionListener:
    tags:
      - {
          name: kernel.event_listener,
          event: kernel.exception,
          method: onKernelException,
        }
