version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - symfony_net
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - symfony_net

  mysql:
    image: mysql:5.7
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfonydb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_net

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react.prod
    container_name: react_frontend
    networks:
      - symfony_net
    depends_on:
      - php

networks:
  symfony_net:
    driver: bridge

volumes:
  mysql_data:
