services:
  # Service PHP (Symfony)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - symfony_net
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfonydb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  # Serveur Nginx pour Symfony
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www/html
      - ./frontend:/var/www/react
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - symfony_net

  # Service MySQL
  mysql:
    image: mysql:5.7
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfonydb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_net

  # Service React (Frontend)
  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.react # Vérifie que ce fichier existe
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173" # Port pour Vite (hot reload)
    networks:
      - symfony_net
    depends_on:
      - php # Optionnel si tu as besoin de communiquer avec le backend Symfony
    environment:
      - VITE_API_PROXY_TARGET=http://nginx:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_pma
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - symfony_net

networks:
  symfony_net:
    driver: bridge

volumes:
  mysql_data:
