api_platform:
  title: Hello API Platform
  version: 1.0.0
  defaults:
    stateless: false
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
    html: ["text/html"]
  swagger:
    api_keys:
      JWT:
        name: Authorization # Nom de l'en-tête pour le token JWT
        type: header # Le token sera envoyé dans l'en-tête HTTP
  