nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["^http://(localhost(:5173)?|nginx)$"]
    allow_credentials: true
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link", "Content-Range", "X-Total-Count"] # <-- AJOUT ICI
    max_age: 3600

  paths:
    "^/api":
      origin_regex: true
      allow_origin: ["^http://(localhost(:5173)?|nginx)$"]
      allow_credentials: true
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      expose_headers: ["Link", "Content-Range", "X-Total-Count"] # <-- AJOUT ICI

nelmio_api_doc:
  documentation:
    info:
      title: "Portfolio"
      description: "Documentation de mon API"
      version: "1.0.0"
    security:
      - Bearer: [] # Utilisation de Bearer pour la sécurité JWT
  areas:
    - name: api
