security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check  # L'ajout de ce chemin est essentiel pour vérifier la soumission de connexion
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email  # Remplacer username par email
                password_path: password

        # Le firewall pour l'API sécurisé par JWT
        # api:
        #     pattern: ^/api
        #     stateless: true
        #     provider: app_user_provider
        #     jwt: ~

    access_control:
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Accès sans authentification pour Swagger
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Accès sans authentification pour login_check
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Accès sans authentification pour l'enregistrement
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  # Toutes les autres routes de l'API nécessitent un JWT
