twig_component:
    anonymous_template_directory: '%kernel.project_dir%/var/cache/twig/components'
    defaults:
        # Namespace & directory for components
        App\Twig\Components\: 'components/'